config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'blogs#index'
  resources :blogs, except: :index
  get ':content', to: 'blogs#content', as: :diff_content

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	# def update_version(blog)
	# 	Blog.where.not(id: id).update_all(current_version: false)
 #    end

    def compare_blog(blog)
      @aa=[]
        doc1 = Nokogiri::HTML(content)
      doc2 = Nokogiri::HTML(blog.content)
      doc2.diff(doc1) do |change,node|
	       
        a="#{change} #{node.to_html}".ljust(30) + node.parent.path
       @aa << a
       
       	
       end
      return @aa
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	def new
        @blog = Blog.new
	end

	def create
      @blog = Blog.new(permit_params)
      if @blogs.save
        redirect_to root_path
      end
  end

  def index
    @current_blog = Blog.find_by(current_version: true)
    @blogs =  Blog.where.not(current_version: true)
  end
  def edit
   @blog = Blog.find(params[:id])
  end

  def update
   @blog = Blog.find(params[:id])
    @blog.update!(title: params["blog"]["title"], content: params["blog"]["content"]) 
   
    # blog.update_version(blog)
    redirect_to root_path
   
  end

  def content

    current_blog = Blog.find_by(id: params[:content])
    second_blog = Blog.find_by(id: params[:format])
    @difference = current_blog.compare_blog(second_blog)
    
  end

  private
    
    def permit_params
     params.require(:blog).permit(:title, :content)

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/content.html.erb
<h2>Difference between two files are  </h2>
<p><%=@difference[-1]%></p>

<p> <%= @difference[-2] %> </p>

app/views/blogs/edit.html.erb
<h1>Create new version </h1>

<%= form_for @blog do |f| %>
  title: <%= f.text_field :title %><br />
  content : <%= f.text_area :content %><br />
  
  <%= f.submit "update version" %>
<% end %>

app/views/blogs/index.html.erb
<h1>Current Version </h1>
<% if @current_blog.present? %>
<p>title: <%= @current_blog.title %> | current version | 

<p> blog content: <%= @current_blog.content %>  </p>
<h3><%= link_to "edit", edit_blog_path(@current_blog) %> | updated at <%=@current_blog.updated_at.strftime("%FT%T") %> </h3> 

</p>
<% end%>
<h1>Previous Versions </h1>
<% if @blogs.present? %>
  <% @blogs.each do | blog| %>
     <p>title: <%= blog.title %> | <%= link_to 'edit', edit_blog_path(blog) %> &nbsp updated at <%=@current_blog.updated_at.strftime("%FT%T") %> </p> <br>
     <p>blog content: <%= blog.content %></p>
     <h3><%= link_to "edit", edit_blog_path(blog) %> | updated at <%=@current_blog.updated_at.strftime("%FT%T") %> </h3> 
  <% end%>

<%end%>

<h3>compare the difference between two files <%= link_to "content diff", diff_content_path(@current_blog, Blog.last)%> </h3>

app/views/blogs/new.html.erb
<%= form_for @blog do |f| %>
  title: <%= f.text_field :title %><br />
  content : <%= f.text_area :content %><br />
  
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gitblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>